# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'WheresMyCar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WheresMyCar
  pod 'SwiftLint'
  pod 'FMDB'

end
